### ISSUE TITLE
Erreur lors de l'envoi d'un paiement à l'API Cyclos

### ISSUE THREAD

**Issue by chbonnin** [jymaire/hellos#12]
Depuis la dernière mise à jour de Cyclos à la version 4.14.12, les insertions de nouveaux paiements par l'API Cyclos échouent.
Hellos affiche l'erreur suivante : [Erreur technique inattendue lors du paiement dans Cyclos]

Le problème a été reproduit en utilisant uniquement l'API Cyclos (https://mlc.sol-reseau.org/elsass/lestuck/api/) avec la commande : 
curl -X POST "https://mlc.sol-reseau.org/elsass/lestuck/api/system/payments" -H  "accept: application/json" -H  "Authorization: Basic bn...==" -H  "Content-Type: application/json" -d "{\"amount\":\"11.0\",\"subject\":\"christ.bonnin@laposte.net\",\"description\":\"Paiement automatique, id technique 13690786\",\"type\":\"EmissionStuck.CreditParticulierStuck\"}"
ce qui provoque l'erreur 404 avec le message 
{
  "entityType": "User", "key": "christ.bonnin@laposte.net"
}
Avez-vous le même pb à la Gonette ?

**Comment by jymaire** [comment]
Bonjour,

Merci pour le retour, je vais essayer de regarder ça dans le semaine. Pour le moment, la personne qui s'en occupe ne m'a rien remonté, je vais voir avec elle.

**Comment by jymaire** [comment]
Après investigation côté Gonette, on a eu quelques soucis ces derniers jours, mais c'était à cause de time out côté Hello Asso. J'ai testé sur mon compte perso, cela a bien fonctionné.

Dans ton message d'erreur, on dirait qu'il ne trouve pas le user avec ton adresse email. Il y a bien un utilisateur avec le bon type qui est associé à cet adresse email ?

**Comment by chbonnin** [comment]
Salut,

Finalement Eric DBA a fini par régler le problème qui venait bien de la 
configuration Cyclos

"Le problème provenait d'une non déclaration du courriel comme 
identifiant d'une transaction via API au niveau de l'utilisateur Technique.
Très probablement lié à la restructuration de configution suite à 
l'intégration Cigogne
Corrigé."

Christian

Le 18/10/2021 à 19:47, MAIRE Jérémy a écrit :
