### ISSUE TITLE
champ Code Catégorie échéancier non pris en compte

### ISSUE THREAD

**Issue by chbonnin** [jymaire/hellos#14]
Merci pour la nouvelle fonctionnalité.
J'ai soumis le fichier de deux lignes que je t'avais envoyé (Echeance_Export_20220217.csv). Il l'a bien pris en compte mais a accepté la dernière ligne alors que le champ Code Catégorie échéancier n'a pas la bonne valeur ('Cha' pour change). Collect.online mélange dans son export les prélèvements pour du change ou pour cotisation (ou autre). Il faut ne prendre que le change

**Comment by jymaire** [comment]
Ah zut, j'avais oublié cette partie là. Je viens de mettre à jour le jar sur le drive (même lien, celui dans la PR) avec la correction et un bouton pour créditer tous les paiements "à faire"

**Comment by jymaire** [comment]
Super, je ferme l'issue et je merge la PR sur la branche principale
